import 'package:hotel/models/Equipement.dart';
import 'package:hotel/models/Hotel.dart';

List<Hotel> hotels = [
  const Hotel(
    id: 1,
    name: 'Hotel le Berceau',
    description: 'Hotel tropical avec un style traditionnel',
    town: 'Notsé',
    views: 52,
    reviews: 17,
    stars: 3,
    imageUrl: 'assets/images/hotels/hotel1.jpg',
  ),
  const Hotel(
    id: 2,
    name: 'Hotel de la Paix',
    description: 'Hôtel de luxe situé au cœur de la ville',
    town: 'Kpalimé',
    views: 43,
    reviews: 10,
    stars: 4,
    imageUrl: 'assets/images/hotels/hotel2.jpg',
  ),
  const Hotel(
    id: 3,
    name: 'Hotel La Roseraie',
    description: 'Hôtel romantique avec un charmant jardin',
    town: 'Lomé',
    views: 35,
    reviews: 6,
    stars: 3,
    imageUrl: 'assets/images/hotels/hotel3.jpg',
  ),
  const Hotel(
    id: 4,
    name: 'Hotel des Alpes',
    description: 'Hôtel de montagne avec vue panoramique',
    town: 'Tsévié',
    views: 58,
    reviews: 12,
    stars: 4,
    imageUrl: 'assets/images/hotels/hotel4.jpeg',
  ),
  const Hotel(
    id: 5,
    name: 'Hotel La Belle Vie',
    description: 'Hôtel design dans un quartier branché',
    town: 'Lomé',
    views: 67,
    reviews: 15,
    stars: 4,
    imageUrl: 'assets/images/hotels/hotel5.jpeg',
  ),
  const Hotel(
    id: 6,
    name: 'Hotel le Château',
    description: 'Hôtel historique dans un cadre pittoresque',
    town: 'Lomé',
    views: 23,
    reviews: 4,
    stars: 3,
    imageUrl: 'assets/images/hotels/hotel6.jpg',
  ),
  const Hotel(
    id: 7,
    name: 'Hotel Le Mirage',
    description: 'Hôtel moderne avec des chambres spacieuses',
    town: 'Lomé',
    views: 42,
    reviews: 11,
    stars: 4,
    imageUrl: 'assets/images/hotels/hotel7.jpeg',
  ),
  const Hotel(
    id: 8,
    name: 'Hotel Le Soleil',
    description: 'Hôtel en bord de mer avec une vue imprenable',
    town: 'Kara',
    views: 72,
    reviews: 20,
    stars: 5,
    imageUrl: 'assets/images/hotels/hotel8.jpg',
  ),
  const Hotel(
      id: 9,
      name: 'Hotel de la Plage',
      description:
          'Hôtel sur la plage, avec vue sur l\'océan et une grande piscine extérieure',
      town: 'Lomé',
      views: 87,
      reviews: 23,
      stars: 4,
      imageUrl: 'assets/images/hotels/hotel9.jpg'),
  const Hotel(
      id: 10,
      name: 'Hotel de la Vallée',
      description:
          'Hôtel de charme en bord de rivière, avec un grand parc et des activités en plein air',
      town: 'Lomé',
      views: 33,
      reviews: 9,
      stars: 3,
      imageUrl: 'assets/images/hotels/hotel10.jpg'),
  const Hotel(
      id: 11,
      name: 'Hotel du Château',
      description:
          'Hôtel historique dans un château du XVIIème siècle, avec des chambres luxueuses et un grand parc',
      town: 'Lomé',
      views: 67,
      reviews: 14,
      stars: 5,
      imageUrl: 'assets/images/hotels/hotel11.jpg'),
  const Hotel(
      id: 12,
      name: 'Hotel du Lac',
      description:
          'Hôtel romantique au bord d\'un lac, avec des chambres élégantes et un restaurant gastronomique',
      town: 'Lomé',
      views: 49,
      reviews: 12,
      stars: 4,
      imageUrl: 'assets/images/hotels/hotel12.jpg'),
  const Hotel(
      id: 13,
      name: 'Hotel des Montagnes',
      description:
          'Hôtel de montagne avec une vue imprenable, un spa et des activités de plein air',
      town: 'Lomé',
      views: 71,
      reviews: 16,
      stars: 4,
      imageUrl: 'assets/images/hotels/hotel13.jpg'),
  const Hotel(
      id: 14,
      name: 'Hotel de la Gare',
      description:
          'Hôtel convivial et familial, à proximité de la gare et des attractions touristiques',
      town: 'Lomé',
      reviews: 8,
      stars: 2,
      imageUrl: 'assets/images/hotels/hotel14.jpeg'),
  const Hotel(
    id: 15,
    name: 'Hôtel Belle Vue',
    description:
        'Situé en bord de mer, l\'Hôtel Belle Vue offre une vue imprenable sur l\'océan.',
    town: 'Lomé',
    views: 120,
    reviews: 38,
    stars: 4,
    imageUrl: 'assets/images/hotels/hotel15.jpg',
  ),
];

List<Hotel> popularsHotels =
    hotels.where((hotel) => hotel.stars! >= 4).toList();

List<Equipement> equipements = [
  const Equipement(
    id: 1,
    imageUrl: 'assets/images/chambres/chambre1.jpg',
    categoryId: 1,
    name: 'Chambre de luxe 05',
    price: 75000,
    isAvailable: true,
  ),
  const Equipement(
    id: 2,
    imageUrl: 'assets/images/picines/picine1.jpg',
    name: 'Picine du nord',
    categoryId: 2,
    price: 75000,
    isAvailable: true,
  ),
  const Equipement(
    id: 3,
    imageUrl: 'assets/images/chambres/chambre2.jpg',
    categoryId: 1,
    name: 'Chambre 2',
    price: 75000,
    isAvailable: true,
  ),
  const Equipement(
    id: 4,
    imageUrl: 'assets/images/chambres/chambre3.jpg',
    categoryId: 1,
    name: 'Chambre 08',
    price: 75000,
    isAvailable: true,
  ),
  const Equipement(
    id: 5,
    imageUrl: 'assets/images/picines/picine2.jpg',
    name: 'Picine à l\entrée',
    categoryId: 2,
    price: 75000,
    isAvailable: true,
  ),
  const Equipement(
    id: 6,
    imageUrl: 'assets/images/chambres/chambre4.jpeg',
    categoryId: 1,
    price: 75000,
    name: 'Chambre 11',
    isAvailable: false,
  ),
  const Equipement(
    id: 7,
    imageUrl: 'assets/images/chambres/chambre5.jpg',
    categoryId: 1,
    price: 75000,
    name: 'Chambre 15',
    isAvailable: true,
  ),
  const Equipement(
    id: 8,
    imageUrl: 'assets/images/chambres/chambre6.jpg',
    categoryId: 1,
    name: 'Chambre 17',
    price: 75000,
    isAvailable: true,
  ),
  const Equipement(
    id: 9,
    imageUrl: 'assets/images/chambres/chambre7.jpg',
    categoryId: 1,
    name: 'Chambre de luxe 12',
    price: 75000,
    isAvailable: false,
  ),
  const Equipement(
    id: 10,
    imageUrl: 'assets/images/picines/picine3.jpg',
    categoryId: 2,
    price: 75000,
    name: 'Picine du sud',
    isAvailable: true,
  ),
  const Equipement(
    id: 11,
    imageUrl: 'assets/images/chambres/chambre9.jpeg',
    categoryId: 1,
    name: 'Chambre pour deux 67',
    price: 75000,
    isAvailable: true,
  ),
];
